### ISSUE TITLE
Add support for local image attachments

### ISSUE THREAD

**Issue by jfunction** [jonocarroll/ntfy#10]
I know there's support for this via URL but it would be nice if we could attach images from a local filename. There's [support for this](https://docs.ntfy.sh/publish/#attach-local-file) which involves sending a PUT request. 

In terms of the user-facing API maybe `attach` can also allow a local file path, in which case it resorts to using PUT and passes in `readBin(attach)`. Wouldn't it be nice if that just magically worked? Anyway, I sat for a bit to make a small working example which could be useful for this.

```r
send_file <- function(topic, message, filename) {
    filedata <- readBin(con = file(filename,'rb'),
                        what='raw',
                        n = file.info(filename)$size)
    httr::PUT(url = paste0("https://ntfy.sh/",topic),
              body = filedata,
              httr::add_headers(.headers=c(filename=filename, message=message)))
  }

# Usage:
send_file(topic='cats', message='Look, a cat!', filename='cat.png')
```

**Comment by jonocarroll** [comment]
Nice, thanks! I have a prototype working riffing on this example, including accepting an as-yet-not-written-to-disk `ggplot` object. PR to follow sometime soon.

**Comment by jonocarroll** [comment]
Extends #2

**Comment by jonocarroll** [comment]
FYI, I plan to leave `attach` doing what it currently does - attaches a file - and will introduce an `image` argument that inlines with `readBin()`.
