### ISSUE TITLE
Send body is unnecessarily quoted

### ISSUE THREAD

**Issue by HenrikBengtsson** [jonocarroll/ntfy#3]
Messages sent with `ntfy_send()` ends up being quoted.  This stems from using `shQuote()` in:

```
function (body = "test", topic = ntfy_topic(), server = ntfy_server(), 
    ...) 
{
    httr::POST(url = paste(server, topic, sep = "/"), body = shQuote(body), 
        ...)
}
```

Replacing `body = shQuote(body)` with `body = body` fixes this problem.

PS. Thanks for writing this wrapper.  It's really neat.  FWIW, I've added it to <https://github.com/HenrikBengtsson/progressr/issues/19>; I think it can be used as a **progressr** backend.

**Comment by jonocarroll** [comment]
Thank you! I recall adding that for a specific reason, but I'll have to do some testing to figure out if it was just while I was prototyping. Potentially to get linebreaks to go through correctly (?) or (reminding myself after reading the README again) I think maybe from when I was testing at the commandline and needed to escape in `"this is a test!"`. I'll throw some more examples at it, but if it all works fine without `shQuote()` then yeah, it can go.

**Comment by jonocarroll** [comment]
Okay, with a bit of testing, I can see that sending a `data.frame` or `list` doesn't work nicely without the `shQuote()`. I believe I originally tested this with `ntfy_send(mtcars)` which tries to go through as `Content-Disposition: form-data` without the `shQuote`.

An alternative is to capture a `data.frame` with e.g. `capture.output()` and this produces a nice result in that case, but isn't as nice for a simple text string (which then has a `[1]` prefix and quotes). 

In [this tiny PR](https://github.com/jonocarroll/ntfy/pull/4) I've exposed an argument so the user can specify which function will capture the output, either `shQuote`, `capture.output`, or perhaps in your use-case, `identity`. Let me know if this solves the problem for you.

**Comment by HenrikBengtsson** [comment]
> I can see that sending a data.frame or list doesn't work nicely without the shQuote(). I believe I originally tested this with ntfy_send(mtcars)

I don't understand, but I'm probably missing something. What does it mean to send a data.frame? What is `ntfy_send(mtcars)` supposed to do?

**Comment by jonocarroll** [comment]
I was hoping to support sending arbitrary data (text, data, images) so that users can receive whatever they want. The notification may tell them that the process is complete, but a table of stats could go with it.

**Comment by HenrikBengtsson** [comment]
I see.  I would consider such "fancy" output to be a layer on top of the low-level ntfy.sh API.  So, my suggestion would be to provide a version of the ntfy.sh API in R, that provides a one-to-one relationship with what's described on https://docs.ntfy.sh/publish/.  The 'Publish as JSON' section (<https://docs.ntfy.sh/publish/#publish-as-json>) has a nice summary:

* `topic`
* `message`
* `title`
* `tags`
* `priority`
* `actions`
* `click`
* `attach`
* `filename`
* `delay`
* `email`

I'm thinking that `ntfy_send()` could have arguments with the same name that maps to these.

Then, for "fancy" output, there could be helper functions that can be used to generate components of the `message` (which you currently call `body` in R).  However, lots of this will be object-to-plain-text conversion, which already exist in many ways in R, so maybe not needed. Instead, the following might be sufficient:

```r
message <- glue::glue(paste(collapse = "\n", c(
   "Processing completed at { Sys.time() }.", 
   "",
   "Results:", 
   "{ paste(capture.output(head(mtcars)), collapse = '\n') }"
)))
ntfy_send(message)
```

To conclude, I don't think there should be any modification done to `body`.

**Comment by jonocarroll** [comment]
Yeah, that sounds like a good plan. I'll try to add the arguments and leave `body` as a straight passthrough (to be constructed by the user). That also addresses #1 and #2 so I think it works in very nicely. Cheers!

**Comment by jonocarroll** [comment]
This PR #5 might resolve this; I've added all the arguments and the `message` is now entirely controlled by the user. Tags and titles work now, too

![notification1](https://user-images.githubusercontent.com/9496865/222935392-4ec5349d-3e46-4310-8a7d-31b5b1dc3c52.png)

![notification2](https://user-images.githubusercontent.com/9496865/222935390-aad930ee-fc65-46f7-a289-08514bab04f2.png)

Is there anything else missing that you need?
