### ISSUE TITLE
Tags list conversion

### ISSUE THREAD

**Issue by coolbutuseless** [jonocarroll/ntfy#6]
I expected this to work:

Ntfy_send(..., Tags = C('cat', 'dog'))

But it produces json ntfy.sh doesn't understand.

Perhaps instead of

If (!is.list(tags))Tags = list(tags)

It could be:

If (!is.list(tags))Tags = as.list(tags)

(I'm on mobile. Please excuse formatting!)

**Comment by jonocarroll** [comment]
Yeah, I probably didn't test that well enough - I'll make that change. Cheers!

**Comment by jonocarroll** [comment]
Closed via #7
